# Generated by Django 3.0.2 on 2020-05-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityPeriod',
            new_name='Activity',
        ),
    ]
