# Generated by Django 3.0.2 on 2020-05-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20200530_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
